export const projectsData = [
    {
        name: "Collabify",
        imageDark: "/project/second_project(dark).png",
        imageLight: "/project/second_project(light).png",
        git: "https://github.com/shabinx30/Collabify",
        live: "https://collabify-shabin.vercel.app",
        description:
            "Designed and developed a web platform that connects brands with content creators for paid promotions. Implemented features including user authentication, creator portfolios, search and filtering, booking system, in app messaging, payment processing, and an admin dashboard.",
        techs: [
            "next.js",
            "socket.io",
            "webrtc",
            "tailewind",
            "typescript",
            "mongodb",
            "node.js",
            "nest.js",
            "jwt",
            "redux",
        ],
    },
    {
        name: "Tungsten",
        image: "/project/first_project.png",
        git: "https://github.com/shabinx30/TUNGSTEN",
        live: "https://tungsten-9vxl.onrender.com/",
        description:
            "Architected and built an E-commerce platform from the ground up, providing an advanced shopping experience for users with full control over product management through an admin module",
        techs: [
            "node.js",
            "express.js",
            "mongodb",
            "razopay",
            "ejs",
            "mvc",
            "bootstrap",
            "node mailer",
            "aws",
            "google auth",
        ],
    },
    {
        name: "Convo",
        imageDark: "/project/convo(dark).png",
        imageLight: "/project/convo(light).png",
        git: "https://github.com/shabinx30/CHAT_APP",
        live: "https://chat-app-taupe-zeta.vercel.app",
        description:
            "Designed a feature-rich chat app with online/offline status, typing indicators, and file sharing. Built with a focus on real time performance and seamless user experience.",
        techs: [
            "react.js",
            "socket.io",
            "tailewind",
            "typescript",
            "mongodb",
            "node.js",
            "express.js",
            "jwt",
            "redux",
            "pwa",
            "cloudinary",
        ],
    },
    {
        name: "User Managment System",
        imageDark: "/project/ums(dark).png",
        imageLight: "/project/ums(light).png",
        git: "https://github.com/shabinx30/UMS-REACT-NODE",
        live: "https://ums-react-node.vercel.app",
        description:
            "Engineered a secure user management system with authentication, user registration, profile management, and admin controls. Implemented protected routes and role-based access control to manage user creation, editing, and deletion efficiently.",
        techs: [
            "react.js",
            "tailewind",
            "typescript",
            "postgres",
            "node.js",
            "express.js",
            "jwt",
            "redux",
        ],
    },
    {
        name: "Netflix",
        image: "/project/netflix_clone.png",
        git: "https://github.com/shabinx30/Netflix_Clone",
        live: "https://netflix-shabin.vercel.app",
        description:
            "Crafted a dynamic video streaming platform with user authentication, movie browsing, trailer viewing, and a personalized favorites section. Focused on delivering a responsive and visually appealing user interface for enhanced user engagement.",
        techs: ["react.js", "tailewind", "firebase", "api"],
    },
    {
        name: "OLX",
        image: "/project/olx_clone.png",
        git: "https://github.com/shabinx30/OLX-Clone",
        live: "https://olx-shabin.vercel.app",
        description:
            "Created a responsive online marketplace with user login/signup and product listing capabilities. Prioritized user experience by delivering a sleek, easy-to-navigate interface.",
        techs: ["react.js", "tailewind", "firebase", "api"],
    },
];
